### ISSUE TITLE
Route parameter(s)

### ISSUE THREAD

**Issue by jrean** [juy/ActiveMenu#9]
Hi,

Great package.

I would like to perform the following:

```
active_route(['
    my.awesome.route.name.show' => [
        'parameter_name' => 'parameter_value',
        'parameter_name' => 'parameter_value',
        //...
    ],
    //...
], 'custom_class_name');

            Route::get('/xxx/xxx/{slug}', [
                'as'   => 'show',
                'uses' => 'XxxxxController@show'
            ]);

```

It involves a refactoring and so I would like to know if you would accept to take care of it?

Thanks

**Comment by angelside** [comment]
We use only "route name" for to identify active status. It's very simple package. For now we do not think  add complex methods. I think laravel universe already have more advanced active menu packages.
